generator:
  default: sdxl-turbo
  sdxl-turbo:
    model_path: "stabilityai/sdxl-turbo"
    guidance_scale: 0.0
    num_inference_steps: 1
    device: "cuda"
    seed: 1
    lora_path: ~

  sdv2:
    model_path: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 10
    num_inference_steps: 35
    device: "cuda"
    seed: 1
    lora_path: ~
  
ranker:
  default: multi
  paligemma: 
  aesthetic:
    