generator:
  sdxl-turbo:
    model_path: "stabilityai/sdxl-turbo"
    seed: 0
    device: cuda
    # generation
    num_images: 5
    num_inference_steps: 4
    guidance_scale: 0
    height: 512
    width: 512
    prefix: "flat color illustration, app icon,"
    suffix: ",inspired by Tom Whalen, atmospheric light, soft color palette, bold outlines, golden hour lighting."
    negative_prompt: ""

  sdv2-1:
    model_path: "stabilityai/stable-diffusion-2-1"
    seed: 0
    device: cuda
    # generation
    num_images: 3
    num_inference_steps: 25
    guidance_scale: 10
    height: 768
    width: 768
    prefix: ""
    suffix: ",by Walenty Wańkowicz, by Grzegorz Rutkowski, 2D illustration, (flat style:1.3), (high contrast:1.3), watercolor painting style, oil paint concept art."
    negative_prompt: ""

converter:
  vtracer-v1:
  # convertion
    limit: 10000

  vtracer-v2:
  # convertion
    limit: 10000

ranker:
  aesthetic:
    model_path: "models/sac+logos+ava1-l14-linearMSE.pth"
    clip_model_path: "models/ViT-L-14.pt"
    seed: 0
    device: cuda

  siglip:
    model_path: "google/siglip-so400m-patch14-384"
    seed: 0
    device: cuda
   
optimizer:
  diffvg:
    args:
      iterations: 200
      jpeg_iter: 200
      aesthetic_iter: 0
      warmup_iter: 0
      log_interval: 10
      w_aesthetic: 100.0
      w_siglip: 100.0
      w_mse: 5000.0
      batch_size: 1
      lr_points: 0.3
      lr_color: 0.01
      grad_clip_norm: 1.0
      similarity_mode: ""
      device: "cuda"
      dtype: torch.float16

